# Generated by Django 5.2.12 on 2026-03-12 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prostor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název prostoru')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Prostor',
                'verbose_name_plural': 'Prostory',
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek', models.DateTimeField(verbose_name='Začátek rezervace')),
                ('konec', models.DateTimeField(verbose_name='Konec rezervace')),
                ('schvaleno', models.BooleanField(default=False, verbose_name='Schváleno obcí')),
                ('prostor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.prostor', verbose_name='Prostor')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
            },
        ),
    ]
