# Generated by Django 5.2.12 on 2026-03-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervace',
            name='email',
            field=models.EmailField(default='neni@zadan.cz', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='rezervace',
            name='jmeno',
            field=models.CharField(default='Neznámý', max_length=50, verbose_name='Jméno'),
        ),
        migrations.AddField(
            model_name='rezervace',
            name='prijmeni',
            field=models.CharField(default='Neznámý', max_length=50, verbose_name='Příjmení'),
        ),
        migrations.AddField(
            model_name='rezervace',
            name='telefon',
            field=models.CharField(default='000000000', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrovaný uživatel'),
        ),
    ]
