# Generated by Django 5.2.13 on 2026-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0004_resetheslakod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='jmeno',
            field=models.CharField(max_length=50, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='prijmeni',
            field=models.CharField(max_length=50, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
    ]
